public enum abilityList { //Will Become HashMap but is an Enum for Now
    none,
    Adaptability,       //STAB +0.5
    Aerilate,           //+20% Damage on Normal Moves & Normal Moves Become Flying
    Aftermath,
    Air_Lock,
    Analytic,           //Lower Speed = +30% Damage
    Anger_Point,
    Anger_Shell,
    Anticipation,
    Arena_Trap,
    Armor_Tail,
    Aroma_Veil,
    As_One,
    Aura_Break,         //Fairy Aura -> -25% Fairy Moves && Dark Aura -> -25% Dark Aura
    Bad_Dreams,
    Ball_Fetch,
    Battery,            //+30% Special Moves ALLIES
    Battle_Armor,
    Battle_Bond,
    Beads_of_Ruin,      //Lower All Special Defense Stats by 25%
    Beast_Boost,
    Berserk,
    Big_Pecks,
    Blaze,              //33% HP = +50% Fire Moves
    Bulletproof,        //Immune to Move List Bullet
    Cheek_Pouch,
    Chilling_Neigh,
    Chlorophyll,        //Sun = Speed x2
    Clear_Body,
    Cloud_Nine,
    Color_Change,
    Comatose,
    Commander,
    Competitive,
    Compound_Eyes,
    Contrary,
    Corrosion,
    Costar,
    Cotton_Down,
    Cud_Chew,
    Curious_Medicine,
    Cursed_Body,
    Cute_Charm,
    Damp,               //Immune to Self Destruct and Explosion
    Dancer,
    Dark_Aura,          //Dark Moves +33%
    Dauntless_Shield,
    Dazzling,           //Immune to Move List Priority > 0
    Defeatist,          //HP <= 50% -> Offense = 50%
    Defiant,
    Delta_Stream,
    Desolate_Land,
    Disguise,
    Download,
    Dragons_Maw,        //Dragon Move -> Offense Multiplied 1.5
    Drizzle,
    Drought,
    Dry_Skin,           //Immune Water Moves && +25% Damage From Fire Moves
    Early_Bird,
    Earth_Eater,        //Immune Ground Moves
    Effect_Spore,
    Electric_Surge,
    Electromorphosis,   //No Calculator Affect but reminder to add Charged Condition, Showdown refuses to add it for "Too much hand holding"
    Embody_Aspect,
    Emergency_Exit,
    Fairy_Aura,         //Fairy Moves +33%
    Filter,             //Super Effective Moves -25%
    Flame_Body,
    Flare_Boost,        //Burn = +50 Special Moves
    Flash_Fire,         //Immune Fire && Hit by Fire -> +50% Offense When Useing Fire Moves
    Flower_Gift,        //Sun = Attack & Special Defense +50% (Include Allies)
    Flower_Veil,
    Fluffy,             //50% Contact Damage && 2x Damage Fire
    Forecast,
    Forewarn,
    Friend_Guard,       //Multi-Battle = -25% Damage to ALLIES ONLY
    Frisk,
    Full_Metal_Body,
    Fur_Coat,           //Double Defense
    Gale_Wings,
    Galvanize,          //+20% Damage on Normal Moves & Normal Moves Become Electric
    Gluttony,
    Good_as_Gold,
    Gooey,
    Gorilla_Tactics,    //Increase Attack by 50%
    Grass_Pelt,         //Grassy Terrain = Defense +50%
    Grassy_Surge,
    Grim_Neigh,
    Guard_Dog,
    Gulp_Missile,
    Guts,               //Non-Volatile Status = +50% Attack
    Hadron_Engine,      //Electric Terrain = Special Attack +33%
    Harvest,
    Healer,
    Heatproof,          //Lowers Opponent's Attack or Special Attack by 50% when using Fire Move && Halves Burn Damage
    Heavy_Metal,        //Doubles Weight
    Honey_Gather,
    Hospitality,
    Huge_Power,         //Doubles Attack Stat
    Hunger_Switch,
    Hustle,             //Increases Attack 50%
    Hydration,
    Hyper_Cutter,
    Ice_Body,
    Ice_Face,
    Ice_Scales,         //Halves Damage From Special Moves
    Illuminate,
    Illusion,
    Immunity,
    Imposter,
    Infiltrator,        //Bypass Reflect, Light Screen, Safeguard, and Mist
    Innards_Out,
    Inner_Focus,
    Insomnia,
    Intimidate,
    Intrepid_Sword,
    Iron_Barbs,
    Iron_Fist,          //Increases Moves 20% in List Punching Moves
    Justified,
    Keen_Eye,
    Klutz,              //Item Buffs and Debuffs = 0
    Leaf_Guard,
    Levitate,
    Libero,             //Also has STAB
    Light_Metal,        //Halves Weight Rounded Down
    Lightning_Rod,      //Electric Immunity
    Limber,
    Lingering_Aroma,
    Liquid_Ooze,
    Liquid_Voice,
    Long_Reach,
    Magic_Bounce,
    Magic_Guard,
    Magician,
    Magma_Armor,
    Magnet_Pull,
    Marvel_Scale,
    Mega_Launcher,
    Merciless,
    Mimicry,
    Minds_Eye,
    Minus,
    Mirror_Armor,
    Misty_Surge,
    Mold_Breaker,
    Moody,
    Motor_Drive,
    Moxie,
    Multiscale,
    Multitype,
    Mummy,
    Mycelium_Might,
    Natural_Cure,
    Neuroforce,
    Neutralizing_Gas,
    No_Guard,
    Normalize,
    Oblivious,
    Opportunist,
    Orichalcum_Pulse,
    Overcoat,
    Overgrow,
    Own_Tempo,
    Parental_Bond,
    Pastel_Veil,
    Perish_Body,
    Pickpocket,
    Pickup,
    Pixilate,
    Plus,
    Poison_Heal,
    Poison_Point,
    Poison_Puppeteer,
    Poison_Touch,
    Power_Construct,
    Power_of_Alchemy,
    Power_Spot,
    Prankster,
    Pressure,
    Primordial_Sea,
    Prism_Armor,
    Propeller_Tail,
    Protean,
    Protosynthesis,
    Psychic_Surge,
    Punk_Rock,
    Pure_Power,
    Purifying_Salt,
    Quark_Drive,
    Queenly_Majesty,
    Quick_Draw,
    Quick_Feet,
    Rain_Dish,
    Rattled,
    Receiver,
    Reckless,
    Refrigerate,
    Regenerator,
    Ripen,
    Rivalry,
    RKS_System,
    Rock_Head,
    Rocky_Payload,
    Rough_Skin,
    Run_Away,
    Sand_Force,
    Sand_Rush,
    Sand_Spit,
    Sand_Stream,
    Sand_Veil,
    Sap_Sipper,
    Schooling,
    Scrappy,
    Screen_Cleaner,
    Seed_Sower,
    Serene_Grace,
    Shadow_Shield,
    Shadow_Tag,
    Sharpness,
    Shed_Skin,
    Sheer_Force,
    Shell_Armor,
    Shield_Dust,
    Shields_Down,
    Simple,
    Skill_Link,
    Slow_Start,
    Slush_Rush,
    Sniper,
    Snow_Cloak,
    Snow_Warning,
    Solar_Power,
    Solid_Rock,
    SoulHeart,
    Soundproof,
    Speed_Boost,
    Stakeout,
    Stall,
    Stalwart,
    Stamina,
    Stance_Change,
    Static,
    Steadfast,
    Steam_Engine,
    Steelworker,
    Steely_Spirit,
    Stench,
    Sticky_Hold,
    Storm_Drain,
    Strong_Jaw,
    Sturdy,
    Suction_Cups,
    Super_Luck,
    Supersweet_Syrup,
    Supreme_Overlord,
    Surge_Surfer,
    Swarm,
    Sweet_Veil,
    Swift_Swim,
    Sword_of_Ruin,
    Symbiosis,
    Synchronize,
    Tablets_of_Ruin,
    Tangled_Feet,
    Tangling_Hair,
    Technician,
    Telepathy,
    Tera_Shell,
    Tera_Shift,
    Teraform_Zero,
    Teravolt,
    Thermal_Exchange,
    Thick_Fat,
    Tinted_Lens,
    Torrent,
    Tough_Claws,
    Toxic_Boost,
    Toxic_Chain,
    Toxic_Debris,
    Trace,
    Transistor,
    Triage,
    Truant,
    Turboblaze,
    Unaware,
    Unburden,
    Unnerve,
    Unseen_Fist,
    Vessel_of_Ruin,
    Victory_Star,
    Vital_Spirit,
    Volt_Absorb,
    Wandering_Spirit,
    Water_Absorb,
    Water_Bubble,
    Water_Compaction,
    Water_Veil,
    Weak_Armor,
    Well_Baked_Body,
    White_Smoke,
    Wimp_Out,
    Wind_Power,
    Wind_Rider,
    Wonder_Guard,
    Wonder_Skin,
    Zen_Mode,
    Zero_to_Hero
}